#!/usr/bin/env python3
"""Minimal Agent Kernel Lite HTTPS relay.

Run this behind TLS at a public origin such as /agent_kernel/api/relay/. The
relay does not decrypt bridge messages; it only forwards JSON request/response
envelopes between the phone web app and a desktop bridge that is polling
outbound.
"""

from __future__ import annotations

import argparse
import json
import queue
import re
import secrets
import threading
import time
from http.server import BaseHTTPRequestHandler, ThreadingHTTPServer
from typing import Any
from urllib.parse import unquote


MAX_BODY_BYTES = 256 * 1024
MAX_PENDING_REQUESTS_PER_ROUTE = 32
MAX_INFLIGHT_RESPONSES = 4096
MAX_ROUTE_TTL_SECONDS = 60 * 60 * 24
MAX_PHONE_WAIT_SECONDS = 120
MAX_DESKTOP_POLL_SECONDS = 60
ROUTE_ID_PATTERN = re.compile(r"^route_[A-Za-z0-9_-]{24,96}$")
PAIRING_CODE_PATTERN = re.compile(r"^[0-9]{6,10}$")
ALLOWED_ORIGINS: set[str] = set()


def read_json(handler: BaseHTTPRequestHandler) -> dict[str, Any]:
    length = int(handler.headers.get("Content-Length") or "0")
    if length <= 0:
        return {}
    if length > MAX_BODY_BYTES:
        raise ValueError("request body is too large")
    return json.loads(handler.rfile.read(length).decode("utf-8"))


def write_json(handler: BaseHTTPRequestHandler, status: int, payload: dict[str, Any]) -> None:
    raw = json.dumps(payload, separators=(",", ":")).encode("utf-8")
    handler.send_response(status)
    handler.send_header("Content-Type", "application/json")
    handler.send_header("Content-Length", str(len(raw)))
    origin = handler.headers.get("Origin")
    if origin and origin in ALLOWED_ORIGINS:
        handler.send_header("Access-Control-Allow-Origin", origin)
        handler.send_header("Vary", "Origin")
        handler.send_header("Access-Control-Allow-Headers", "content-type")
        handler.send_header("Access-Control-Allow-Methods", "GET,POST,OPTIONS")
    handler.end_headers()
    handler.wfile.write(raw)


class RelayState:
    def __init__(self) -> None:
        self.lock = threading.Lock()
        self.routes: dict[str, dict[str, Any]] = {}
        self.responses: dict[str, queue.Queue[dict[str, Any]]] = {}
        self.response_expires_at: dict[str, float] = {}

    def cleanup(self) -> None:
        now = time.time()
        with self.lock:
            expired = [
                route_id for route_id, route in self.routes.items()
                if float(route.get("expires_at") or 0) < now
            ]
            for route_id in expired:
                self.routes.pop(route_id, None)
            stale_responses = [
                request_id for request_id, expires_at in self.response_expires_at.items()
                if float(expires_at or 0) < now
            ]
            for request_id in stale_responses:
                self.responses.pop(request_id, None)
                self.response_expires_at.pop(request_id, None)

    def register(self, body: dict[str, Any]) -> dict[str, Any]:
        self.cleanup()
        route_id = str(body.get("route_id") or "").strip()
        if not route_id:
            route_id = f"route_{secrets.token_urlsafe(32)}"
        if not ROUTE_ID_PATTERN.match(route_id):
            raise ValueError("route_id must be generated by the desktop bridge")
        pairing_code = str(body.get("pairing_code") or "").strip()
        if pairing_code and not PAIRING_CODE_PATTERN.match(pairing_code):
            raise ValueError("pairing_code must be 6-10 digits")
        device_id = str(body.get("device_id") or f"desktop_{secrets.token_urlsafe(8)}")
        token = str(body.get("token") or secrets.token_urlsafe(32))
        ttl = max(300, min(int(body.get("ttl_seconds") or MAX_ROUTE_TTL_SECONDS), MAX_ROUTE_TTL_SECONDS))
        route = {
            "route_id": route_id,
            "pairing_code": pairing_code,
            "device_id": device_id,
            "token": token,
            "created_at": time.time(),
            "expires_at": time.time() + ttl,
            "requests": queue.Queue(maxsize=MAX_PENDING_REQUESTS_PER_ROUTE),
            "label": str(body.get("label") or "Agent Kernel Desktop"),
        }
        with self.lock:
            self.routes[route_id] = route
        return {
            "status": "registered",
            "route_id": route_id,
            "pairing_code": pairing_code,
            "device_id": device_id,
            "expires_at": route["expires_at"],
        }

    def route_for_desktop(self, body: dict[str, Any]) -> dict[str, Any]:
        self.cleanup()
        device_id = str(body.get("device_id") or "")
        token = str(body.get("token") or "")
        with self.lock:
            for route in self.routes.values():
                if route.get("device_id") == device_id and route.get("token") == token:
                    return route
        raise ValueError("desktop route is not registered")

    def route_for_phone(self, route_id: str) -> dict[str, Any]:
        self.cleanup()
        if not ROUTE_ID_PATTERN.match(route_id):
            raise ValueError("invalid desktop route")
        with self.lock:
            route = self.routes.get(route_id)
        if not route:
            raise ValueError("paired desktop is not connected to relay")
        return route


class Handler(BaseHTTPRequestHandler):
    state = RelayState()

    def log_message(self, fmt: str, *args: Any) -> None:
        print(f"[relay] {self.address_string()} {fmt % args}", flush=True)

    def do_OPTIONS(self) -> None:
        write_json(self, 204, {})

    def do_GET(self) -> None:
        if self.path.split("?", 1)[0] == "/health":
            self.state.cleanup()
            write_json(self, 200, {"status": "ok", "routes": len(self.state.routes)})
            return
        if self.path.startswith("/desktop/"):
            write_json(self, 405, {"status": "error", "error": "desktop endpoints require POST"})
            return
        if self.path.startswith("/bridge/"):
            self.forward_phone_request("GET")
            return
        write_json(self, 404, {"status": "error", "error": "not found"})

    def do_POST(self) -> None:
        path = self.path.split("?", 1)[0]
        try:
            if path == "/desktop/register":
                write_json(self, 200, self.state.register(read_json(self)))
            elif path == "/desktop/poll":
                self.handle_desktop_poll(read_json(self))
            elif path == "/desktop/respond":
                self.handle_desktop_response(read_json(self))
            elif path.startswith("/bridge/"):
                self.forward_phone_request("POST")
            else:
                write_json(self, 404, {"status": "error", "error": "not found"})
        except Exception as exc:
            write_json(self, 400, {"status": "error", "error": str(exc)})

    def handle_desktop_poll(self, body: dict[str, Any]) -> None:
        route = self.state.route_for_desktop(body)
        timeout = max(5, min(int(body.get("timeout_seconds") or 25), MAX_DESKTOP_POLL_SECONDS))
        try:
            request = route["requests"].get(timeout=timeout)
            write_json(self, 200, {"status": "request", "request": request})
        except queue.Empty:
            write_json(self, 200, {"status": "idle"})

    def handle_desktop_response(self, body: dict[str, Any]) -> None:
        self.state.route_for_desktop(body)
        request_id = str(body.get("request_id") or "")
        if not request_id:
            raise ValueError("request_id is required")
        with self.state.lock:
            response_queue = self.state.responses.pop(request_id, None)
            self.state.response_expires_at.pop(request_id, None)
        if not response_queue:
            raise ValueError("request is no longer waiting")
        response_queue.put({
            "status_code": int(body.get("status_code") or 200),
            "payload": body.get("payload") if isinstance(body.get("payload"), dict) else {},
        })
        write_json(self, 200, {"status": "ok"})

    def forward_phone_request(self, method: str) -> None:
        parts = self.path.split("?", 1)[0].split("/")
        if len(parts) < 4:
            write_json(self, 404, {"status": "error", "error": "bridge route path is incomplete"})
            return
        route_id = unquote(parts[2])
        bridge_path = "/" + "/".join(parts[3:])
        route = self.state.route_for_phone(route_id)
        request_id = f"req_{secrets.token_urlsafe(18)}"
        with self.state.lock:
            if len(self.state.responses) >= MAX_INFLIGHT_RESPONSES:
                write_json(self, 503, {"status": "error", "error": "relay is busy"})
                return
        response_queue: queue.Queue[dict[str, Any]] = queue.Queue(maxsize=1)
        with self.state.lock:
            self.state.responses[request_id] = response_queue
            self.state.response_expires_at[request_id] = time.time() + MAX_PHONE_WAIT_SECONDS
        try:
            route["requests"].put({
                "request_id": request_id,
                "method": method,
                "path": bridge_path,
                "origin": str(self.headers.get("Origin") or ""),
                "body": read_json(self) if method == "POST" else {},
            }, timeout=2)
        except queue.Full:
            with self.state.lock:
                self.state.responses.pop(request_id, None)
                self.state.response_expires_at.pop(request_id, None)
            write_json(self, 429, {"status": "error", "error": "desktop route is busy"})
            return
        try:
            response = response_queue.get(timeout=MAX_PHONE_WAIT_SECONDS)
            write_json(self, int(response.get("status_code") or 200), response.get("payload") or {})
        except queue.Empty:
            with self.state.lock:
                self.state.responses.pop(request_id, None)
                self.state.response_expires_at.pop(request_id, None)
            write_json(self, 504, {"status": "error", "error": "desktop bridge did not respond in time"})


def parse_args() -> argparse.Namespace:
    parser = argparse.ArgumentParser(description="Run the Agent Kernel Lite relay service.")
    parser.add_argument("--host", default="127.0.0.1")
    parser.add_argument("--port", type=int, default=45732)
    parser.add_argument(
        "--allow-origin",
        action="append",
        default=[],
        help="Allowed browser origin for CORS. Repeat for more origins. Omit when serving same-origin.",
    )
    return parser.parse_args()


def main() -> None:
    args = parse_args()
    ALLOWED_ORIGINS.update(str(origin).rstrip("/") for origin in args.allow_origin if str(origin).strip())
    server = ThreadingHTTPServer((str(args.host), int(args.port)), Handler)
    print(f"Agent Kernel Lite relay listening on http://{args.host}:{args.port}", flush=True)
    print("Put this behind HTTPS for browser/mobile use.", flush=True)
    server.serve_forever()


if __name__ == "__main__":
    main()
